name: makavelisoundboard
description: Quotes from the most famous tipster in the balkans, "Daskalos Makaveli" 
version: 1.0.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  audioplayers: ^0.20.1
  share: ^2.0.4
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  integration_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/images/crown.png

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/images/